# Generated by Django 5.2 on 2026-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
            ],
        ),
    ]
