# Generated by Django 6.0.6 on 2026-06-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_approvisionnement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approvisionnement',
        ),
    ]
