# Generated by Django 6.0.6 on 2026-06-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_delete_approvisionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_approvisionnement', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.CharField(max_length=200)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.produit')),
            ],
        ),
    ]
