# Generated by Django 6.0.6 on 2026-06-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvisionnement',
            options={'ordering': ['-date_approvisionnement']},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_vente']},
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='stockapp.categorie'),
        ),
        migrations.CreateModel(
            name='AlerteRupture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('critique', 'Critique')], default='alerte', max_length=10)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='stockapp.produit')),
            ],
            options={
                'verbose_name': 'Alerte rupture',
                'verbose_name_plural': 'Alertes ruptures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
