# Generated by Django 6.0.6 on 2026-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_alter_approvisionnement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
