# Generated by Django 6.0.6 on 2026-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_produit_prix_unitaire_vente_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
