# Generated by Django 6.0.6 on 2026-08-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_alter_alerterupture_options_alter_categorie_options_and_more'),
        ('stockapp', '0010_produit_prix_achat_vente_prix_achat'),
    ]

    operations = [
    ]
