# Generated by Django 6.0.6 on 2026-08-13 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_merge_20260812_1835'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock_maximum',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('VENTE', 'Vente client'), ('ACHAT', 'Achat / Approvisionnement'), ('RETOUR', 'Retour produit'), ('AJUSTEMENT', 'Ajustement manuel'), ('INVENTAIRE', "Régularisation d'inventaire")], max_length=20)),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stockapp.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
