# Generated by Django 6.0.6 on 2026-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_produit_stock_maximum_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_barres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='unité', max_length=50),
        ),
    ]
