# Generated by Django 6.0.6 on 2026-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0013_produit_code_barres_produit_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte Bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit / Avoir')], default='ESPECES', max_length=50),
        ),
        migrations.AddField(
            model_name='vente',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='reference_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
