# Generated by Django 6.0.6 on 2026-09-12 14:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0015_client_fournisseur_vente_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Coût unitaire d'achat", max_digits=12),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='statut',
            field=models.CharField(choices=[('RECU', 'Reçu / En stock'), ('COMMANDE', 'Commandé / En cours'), ('ANNULE', 'Annulé')], default='RECU', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
