# Generated by Django 6.0.6 on 2026-09-15 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0016_approvisionnement_cout_unitaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('LOYER', 'Loyer & Charges locatives'), ('SALAIRE', 'Salaires & Rémunérations'), ('ELECTRICITE', 'Électricité & Eau'), ('INTERNET', 'Télécoms & Internet'), ('TRANSPORT', 'Transport & Logistique'), ('MARKETING', 'Publicité & Marketing'), ('FOURNITURE', 'Fournitures de bureau'), ('MAINTENANCE', 'Entretien & Réparations'), ('TAXE', 'Impôts & Taxes'), ('AUTRE', 'Autre charge opérationnelle')], default='AUTRE', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('beneficiaire', models.CharField(blank=True, max_length=200, null=True)),
                ('justificatif', models.CharField(blank=True, help_text='Numéro de reçu ou facture', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense / Charge',
                'verbose_name_plural': 'Dépenses & Charges',
                'ordering': ['-date_depense', '-date_creation'],
            },
        ),
    ]
