# Generated by Django 6.0.6 on 2026-09-16 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0017_depense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION_PRIX', 'Changement de Prix'), ('MODIFICATION', 'Modification Fiche'), ('SUPPRESSION', 'Suppression'), ('AJUSTEMENT_STOCK', 'Ajustement de Stock'), ('VENTE', 'Vente / Encaissement'), ('REGLEMENT_DETTE', 'Règlement Dette / Créance'), ('DEPENSE', 'Charge OPEX'), ('CONNEXION', 'Connexion / Sécurité')], max_length=30)),
                ('module', models.CharField(choices=[('PRODUIT', 'Produits & Tarifs'), ('STOCK', 'Stock & Inventaire'), ('VENTE', 'Ventes & Caisse POS'), ('APPROVISIONNEMENT', 'Approvisionnements'), ('FOURNISSEUR', 'Fournisseurs & Dettes'), ('CLIENT', 'Clients & Crédits'), ('FINANCES', 'Finances & OPEX'), ('SECURITE', 'Sécurité & Rôles')], max_length=30)),
                ('objet_concerne', models.CharField(help_text='Entité visée (ex: Produit #12, Vente TCK-...)', max_length=255)),
                ('description', models.TextField(help_text="Détail explicatif de l'opération (valeurs avant/après, motif)")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-date_creation'],
            },
        ),
    ]
