# Generated by Django 6.0.6 on 2026-09-16 13:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0018_journalaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION_PRIX', 'Changement de Prix'), ('MODIFICATION', 'Modification Fiche'), ('SUPPRESSION', 'Suppression'), ('AJUSTEMENT_STOCK', 'Ajustement de Stock'), ('VENTE', 'Vente / Encaissement'), ('CLOTURE_CAISSE', 'Clôture Caisse (Rapport Z)'), ('REGLEMENT_DETTE', 'Règlement Dette / Créance'), ('DEPENSE', 'Charge OPEX'), ('CONNEXION', 'Connexion / Sécurité')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='module',
            field=models.CharField(choices=[('PRODUIT', 'Produits & Tarifs'), ('STOCK', 'Stock & Inventaire'), ('VENTE', 'Ventes & Caisse POS'), ('CAISSE', 'Caisse & Sessions'), ('APPROVISIONNEMENT', 'Approvisionnements'), ('FOURNISSEUR', 'Fournisseurs & Dettes'), ('CLIENT', 'Clients & Crédits'), ('FINANCES', 'Finances & OPEX'), ('SECURITE', 'Sécurité & Rôles')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Numéro officiel Rapport Z (ex: Z-20260916-001)', max_length=60, unique=True)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cloture', models.DateTimeField(default=django.utils.timezone.now)),
                ('fond_de_caisse_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monnaie de départ dans le tiroir', max_digits=12)),
                ('total_especes_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_carte_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_mobile_money_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cheque_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_credit_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ventes_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_remises', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ventes_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nombre_tickets', models.PositiveIntegerField(default=0)),
                ('nombre_articles', models.PositiveIntegerField(default=0)),
                ('montant_especes_reel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total espèces compté dans le tiroir', max_digits=12)),
                ('montant_carte_reel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total télécollecte TPE', max_digits=12)),
                ('montant_mobile_money_reel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total relevé Mobile Money', max_digits=12)),
                ('montant_cheque_reel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total chèques en portefeuille', max_digits=12)),
                ('ecart_especes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ecart_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut_conformite', models.CharField(choices=[('CONFORME', 'Conforme (Écart nul)'), ('EXCEDENT', 'Excédentaire (+ Encaissé en trop)'), ('DEFICIT', 'Déficitaire (- Manquant en caisse)')], default='CONFORME', max_length=20)),
                ('commentaire', models.TextField(blank=True, help_text="Justification d'un éventuel écart ou note de passation", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clôture de Caisse (Rapport Z)',
                'verbose_name_plural': 'Clôtures de Caisse (Rapports Z)',
                'ordering': ['-date_cloture', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='cloture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='stockapp.cloturecaisse'),
        ),
    ]
