# Generated by Django 6.0.6 on 2026-09-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0019_alter_journalaudit_action_alter_journalaudit_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='module',
            field=models.CharField(choices=[('PRODUIT', 'Produits & Tarifs'), ('STOCK', 'Stock & Inventaire'), ('VENTE', 'Ventes & Caisse POS'), ('CAISSE', 'Caisse & Sessions'), ('APPROVISIONNEMENT', 'Approvisionnements'), ('FOURNISSEUR', 'Fournisseurs & Dettes'), ('CLIENT', 'Clients & Crédits'), ('FINANCES', 'Finances & OPEX'), ('SECURITE', 'Sécurité & Rôles'), ('NOTIFICATION', "Centre d'Alertes & Notifications")], max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('STOCK_RUPTURE', 'Rupture de Stock'), ('STOCK_FAIBLE', "Seuil d'Alerte Stock"), ('DETTE_FOURNISSEUR', 'Dette Fournisseur'), ('CREANCE_CLIENT', 'Créance Client'), ('ANOMALIE_CAISSE', 'Anomalie de Caisse'), ('SYSTEME', 'Information Système')], default='SYSTEME', max_length=30)),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=15)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, help_text="Lien d'action rapide", max_length=255, null=True)),
                ('cle_unicite', models.CharField(blank=True, db_index=True, help_text="Clé de déduplication d'alerte (ex: stock_rupture_12)", max_length=150, null=True)),
                ('est_lue', models.BooleanField(db_index=True, default=False)),
                ('est_archivee', models.BooleanField(db_index=True, default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(blank=True, help_text='Destinataire spécifique ou null pour visibilité équipe/staff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
